### ISSUE TITLE
question: Is `step{,64}` allowed to panic?

### ISSUE THREAD

**Issue by duesee** [dequbed/rsasl#38]
Should `step{,64}` be allowed to panic, e.g., when called after `Finished` or due to other errors?

### LOGIN

Stepping through LOGIN seems to "fuse" the stepping. This is what I would expect. But maybe there are reasons not to.

```imap
* ok [capability auth=login] asd
A1 AUTHENTICATE LOGIN
+ ...
QWzCuWNl
+ ...
UGHCssKydzByZA==
+ ...
*// I send this due to `error=MechanismDone`
+ ...
*// I send this due to `error=MechanismDone`
+ ...
*// I send this due to `error=MechanismDone`
```

### PLAIN

Stepping through PLAIN seems to repeat the last step. Is this how it should be? :-)

```imap
* ok [capability auth=plain] asd
A1 AUTHENTICATE PLAIN
+ ...
AEFswrljZQBQYcKywrJ3MHJk
+ ...
AEFswrljZQBQYcKywrJ3MHJk
+ ...
AEFswrljZQBQYcKywrJ3MHJk
+ ...
AEFswrljZQBQYcKywrJ3MHJk
+ ...
AEFswrljZQBQYcKywrJ3MHJk
```

### SCRAM-SHA-256

Stepping through SCRAM-SHA-256 (with bad input) panics when we call `step` after we receive the first error.

```imap
* ok [capability auth=scram-sha-256] asd
A1 AUTHENTICATE SCRAM-SHA-256
+ ...
biwsbj1BbMK5Y2Uscj0qTWNzYmN3XjFEMSl1NWxgJ3RgPiNmYWc=
+ ...
*// I send this due to `error=InputDataRequired`
+ ...
// thread 'main' panicked at rsasl-2.0.0/src/mechanisms/scram/client.rs:485:21:
State machine in invalid state
```

**Comment by dequbed** [comment]
> Should `step{,64}` be allowed to panic, e.g., when called after `Finished` or due to other errors?

`step` and `step64` are allowed any behaviour, including panicking, if called after `State::Finished` was returned. I thought I clarified that in the documentation but I must have missed that.

> ### PLAIN
> 
> Stepping through PLAIN seems to repeat the last step. Is this how it should be? :-)

In short, yes. PLAIN doesn't keep any state because it always only consists of one step, so the mechanism can't know it has been called multiple times.

> ### SCRAM-SHA-256
> 
> Stepping through SCRAM-SHA-256 (with bad input) panics when we call `step` after we receive the first error.

Errors in particular may leave the mechanism state machine in an erroring state, so you must not call `step` after an error occured. I'll also add this to the documentation.
