### ISSUE TITLE
Integration of `2.0.0-preview9`

### ISSUE THREAD

**Issue by Mathieu-Lala** [dequbed/rsasl#5]
Hello there :wave: 

I have been updating `rsasl` to the latest version on our project : https://github.com/viridIT/vSMTP/pull/536
But my test with the `PLAIN` protocol fails now, where before they were passing (see [CI result](https://github.com/viridIT/vSMTP/runs/8092983246?check_suite_focus=true)). 

Can you tell me if you test are indeed wrong, or if there is a problem with the `PLAIN` implementation ?

Also, I saw that you do not have CI yet in your project, I can add these to your repo if you wish https://github.com/viridIT/vSMTP/blob/develop/.github/workflows/ci.yaml

And if you needs hands to write `unit tests`, do not hesitate to create an issue with the label `help wanted` 

Thank you a lot for you works

**Comment by dequbed** [comment]
This is most likely a bug in rsasl, specifically that I accidentally registered the new `XOAUTH2` mechanism under the name 'PLAIN' (because I copy-pasted slightly too much).
I added a [note about that in the CHANGELOG.md](https://github.com/dequbed/rsasl/blob/main/CHANGELOG.md#v200-preview11--2022-08-25) when I fixed it & released `-preview11`.

Since rsasl selects mechanisms by their name and chooses the first matching option this resulted in rsasl wrongly expecting XOAUTH2 authentication which is in a different format — and then the reason for the `MechanismError(InvalidFormat)` you see.

If you missed that information in the Changelog, would something like e.g. an ERRATA file containing specifically only those fixed issue have helped? Or a GitHub issue that I directly close with the fix explained?

If the problem persists when you update to `-preview11` or later, please do re-open this issue.

**Comment by dequbed** [comment]
Regarding CI and unit tests, thanks for the offer :)

I'll likely come back to you on that, rsasl does really need much more extensive testing. I'm working on that! ^^

**Comment by Mathieu-Lala** [comment]
Your `CHANGELOG.md` is great ! I just looked at the documentation of the latest version on https://docs.rs/rsasl/latest/rsasl :+1:

**Comment by dequbed** [comment]
That is a really good point actually!

I've added the CHANGELOG to the [rustdocs output](https://docs.rs/rsasl/2.0.0-preview12/rsasl/docs/changelog/index.html) like I do with the README and added a [note in the main crate documentation](https://docs.rs/rsasl/2.0.0-preview12/rsasl/index.html#important-note-for-users-of-this-crate) pointing to it.

**Comment by Mathieu-Lala** [comment]
I just realize I thought 2.0.0-preview9 was the latest release, but I got tricked by the sorting algorithm of docs.rs 😅 , will try with the 2.0.0-preview12

**Comment by dequbed** [comment]
Yeah, it should have been `2.0.0-preview.<num>` ^^'

**Comment by dequbed** [comment]
I published a new pre-release channel 'rc', so `2.0.0-preview12` is released as `2.0.0-rc.1` too. That way the release is considered larger than any -preview* ones and the number after the `rc.` should be compared numerically so a rc.10 would be larger than rc.9.
That should also mean that you should now be able to specify a dependency on rsasl as `^2.0.0-rc.1` (the caret is required) and get the latest rc.XX, whichever that may be.
